name: AI Translation CLI

run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

# Problem is that if there's many PR's i.e. fixing small typos
on:
  push:
    branches: [test]

jobs:
  build:
    if: ${{ contains(github.event.commits[0].message, '[skip build]') }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 20.x]

    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Run Translation CLI
        run: ai-translator-cli -i test.json -o {{lang}}_test.json -l es

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply file changes