name: AI Translation CLI

run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

# Problem is that if there's many PR's i.e. fixing small typos
on:
  push:
    branches: [test]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      # Steps to check what json files have changed
      - name: Get all changed *.js file(s) or any file in the static folder excluding the docs folder
        id: changed-files-excluded
        uses: tj-actions/changed-files@v36
        with:
          files: |
            **/*.json
          files_ignore: es*

      - name: Run step if any *.json file(s) have changed
        if: steps.changed-files-excluded.outputs.any_changed == 'true'
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
            node index -i $file -o {{lang}}_$file -l es -s ${{ secrets.OPENAI_SECRET }}
          done

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply file changes
